#### 2.1 Import Data and Required Packages

Importing Pandas,Numpy,Seaborn,Matplotlib and Warnings Library

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

Import the CSV data as a Pandas DataFrame

In [28]:
df = pd.read_csv(r"Visadataset.csv")

In [29]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [30]:
df.shape

(25480, 12)

In [31]:
df.describe()

       no_of_employees   yr_of_estab  prevailing_wage
count     25480.000000  25480.000000     25480.000000
mean       5667.043210   1979.409929     74455.814592
std       22877.928848     42.366929     52815.942327
min         -26.000000   1800.000000         2.136700
25%        1022.000000   1976.000000     34015.480000
50%        2109.000000   1997.000000     70308.210000
75%        3504.000000   2005.000000    107735.512500
max      602069.000000   2016.000000    319210.270000

In [32]:
df.info

<bound method DataFrame.info of          case_id continent education_of_employee has_job_experience  \
0         EZYV01      Asia           High School                  N
1         EZYV02      Asia              Master's                  Y
2         EZYV03      Asia            Bachelor's                  N
3         EZYV04      Asia            Bachelor's                  N
4         EZYV05    Africa              Master's                  Y
...          ...       ...                   ...                ...
25475  EZYV25476      Asia            Bachelor's                  Y
25476  EZYV25477      Asia           High School                  Y
25477  EZYV25478      Asia              Master's                  Y
25478  EZYV25479      Asia              Master's                  Y
25479  EZYV25480      Asia            Bachelor's                  Y

      requires_job_training  no_of_employees  yr_of_estab  \
0                         N            14513         2007
1                         N             2412         2002
2                         Y            44444         2008
3                         N               98         1897
4                         N             1082         2005
...                     ...              ...          ...
25475                     Y             2601         2008
25476                     N             3274         2006
25477                     N             1121         1910
25478                     Y             1918         1887
25479                     N             3195         1960

      region_of_employment  prevailing_wage unit_of_wage full_time_position  \
0                     West         592.2029         Hour                  Y
1                Northeast       83425.6500         Year                  Y
2                     West      122996.8600         Year                  Y
3                     West       83434.0300         Year                  Y
4                    South      149907.3900         Year                  Y
...                    ...              ...          ...                ...
25475                South       77092.5700         Year                  Y
25476            Northeast      279174.7900         Year                  Y
25477                South      146298.8500         Year                  N
25478                 West       86154.7700         Year                  Y
25479              Midwest       70876.9100         Year                  Y

      case_status
0          Denied
1       Certified
2          Denied
3          Denied
4       Certified
...           ...
25475   Certified
25476   Certified
25477   Certified
25478   Certified
25479   Certified

[25480 rows x 12 columns]>

#### 3.Exploring Data

In [36]:
# define numerical & categorical columns
numeric_features = [feature for feature in df.columns if df[feature].dtype != 'O']
categorical_features = [feature for feature in df.columns if df[feature].dtype == 'O']

# print columns
print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 3 numerical features : ['no_of_employees', 'yr_of_estab', 'prevailing_wage']

We have 9 categorical features : ['case_id', 'continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'region_of_employment', 'unit_of_wage', 'full_time_position', 'case_status']

In [34]:
friend_list = ['A','B','C','D']
for f in friend_list:
  print("Hello"+f)

HelloA
HelloB
HelloC
HelloD

In [35]:
friend_list = ['A','B','C','D']
f for f in friend_list:
  print("Hello"+f)

SyntaxError: invalid syntax (2610867224.py, line 2)

In [ ]:
friend_list = ['A','B','C','D']
g for f in friend_list:
  print("Hello"+f)

SyntaxError: invalid syntax (590847289.py, line 2)

In [ ]:
friend_list = ['A','B','C','D']
new_list = [f for f in friend_list]
print (new_list)

['A', 'B', 'C', 'D']

In [ ]:
friend_list = ['A','B','C','D']
new_list = [g for f in friend_list]
print (new_list)

NameError: name 'g' is not defined

In [ ]:
friend_list = ['A','B','C','D']
new_list = [g for g in friend_list]
print (new_list)

['A', 'B', 'C', 'D']

In [ ]:
# f for f or g for g, in variable_name sirf [] me chalta hai (nyi list bnane ke liye)
# for f in or for g in variable_name bina brackets ke chalta hai (print ya calculation krne ke liye)
#jb hm shuru me f (ya koi value) likhte hai to python ise ek list bnane ka shortcut samzta hai,
#  esliye [] jruri hota hai ,jaise ki upr ka code

In [ ]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [ ]:
df[feature].dtype

NameError: name 'feature' is not defined

In [ ]:
'''Gemini said 

1. The Variables

numeric_features: This is a list containing the names of columns that hold quantitative data
(e.g., Age, Price, Salary).

categorical_features: This is a list containing the names of columns that hold qualitative data or labels 
(e.g., Gender, Color, Country).

2. The Logic


The code uses the .format() method to plug specific values into a string of text:

len(...): This calculates the count (length) of how many features are in that list.

The {} placeholders: These act as "empty seats." The first {} gets filled by the count, 
and the second {} gets filled by the actual list of names.

\n: This is a "newline" character that adds a blank line between the two print statements for better readability.

3. What the Output Looks Like

If you were analyzing a dataset of used cars, the output might look like this:

We have 2 numerical features : ['Price', 'Mileage']

We have 2 categorical features : ['Brand', 'Fuel_Type']'''

### Proportion of count Data in categorical columns

In [38]:
for col in categorical_features:
    print (df[col].value_counts(normalize=True) * 100)
    print('-------------------------------')

case_id
EZYV01       0.003925
EZYV16995    0.003925
EZYV16993    0.003925
EZYV16992    0.003925
EZYV16991    0.003925
               ...
EZYV8492     0.003925
EZYV8491     0.003925
EZYV8490     0.003925
EZYV8489     0.003925
EZYV25480    0.003925
Name: proportion, Length: 25480, dtype: float64
-------------------------------
continent
Asia             66.173469
Europe           14.646782
North America    12.919937
South America     3.343799
Africa            2.162480
Oceania           0.753532
Name: proportion, dtype: float64
-------------------------------
education_of_employee
Bachelor's     40.164835
Master's       37.810047
High School    13.422292
Doctorate       8.602826
Name: proportion, dtype: float64
-------------------------------
has_job_experience
Y    58.092622
N    41.907378
Name: proportion, dtype: float64
-------------------------------
requires_job_training
N    88.402669
Y    11.597331
Name: proportion, dtype: float64
-------------------------------
region_of_employment
Northeast    28.237834
South        27.539246
West         25.847724
Midwest      16.903454
Island        1.471743
Name: proportion, dtype: float64
-------------------------------
unit_of_wage
Year     90.117739
Hour      8.465463
Week      1.067504
Month     0.349294
Name: proportion, dtype: float64
-------------------------------
full_time_position
Y    89.375981
N    10.624019
Name: proportion, dtype: float64
-------------------------------
case_status
Certified    66.789639
Denied       33.210361
Name: proportion, dtype: float64
-------------------------------

In [42]:
employees_number = df['no_of_employees'].tolist()
print(employees_number)

[14513, 2412, 44444, 98, 1082, 2339, 4985, 3035, 4810, 2251, 2465, 4069, 123876, 1652, 15756, 4897, 76638, 2747, 4743, 843, 880, 1706, 2878, 1517, 241, 1100, 756, 2889, 18, 758, 1408, 995, 2415, 2395, 1809, 5512, 2520, 44, 2206, 3729, 3723, 1209, 19770, 2582, 5407, 2092, 2623, 226, 2405, 2171, 746, 3129, 1647, 2438, 11733, 2368, 779, 2825, 3510, 2624, 5340, 2311, 5110, 1316, 100, 2021, 80, 2070, 2654, 292, 1320, 1722, 3339, 452, 3705, 85, 2423, 1274, 1549, 1062, 32619, 4036, 39, 2359, 1023, 2480, 1255, 4455, 2543, 1359, 2324, 4103, 3667, 488, 2724, 1392, 2573, 3524, 1847, 107535, 2227, 334, 224, 367, 306, 2317, 890, 2002, 2903, 2504, 951, 1327, 2421, 1019, 1048, 3323, 509, 2225, 1641, 1144, 2334, 1415, 2754, 1099, 960, 2750, 2753, 23287, 2140, 4499, 2554, 1333, 928, 4289, 113282, 1948, 1933, 2847, 1195, 54, 4390, 73909, 545, 2831, 1634, 1810, 3290, 472, 4273, 2326, 50351, 2261, 255, 373, 22, 3102, 5147, 284, 1926, 2510, 1200, 337, 2880, 816, 2640, 4190, 459, 3351, 3639, 373, 201, 5461, 3050, 28592, 3207, 5820, 3229, 2708, 2779, 977, 44069, 1566, 4439, 1929, 654, 557, 421, 600, 1551, 2540, 961, 3726, 4045, 128431, 2180, 872, 2689, 2752, 1375, 7320, 3282, 1313, 3128, 4757, 2122, 2524, 766, 1190, 2741, 3233, 2696, 3980, 111, 5396, 2778, 789, 1515, 26891, 1867, 3395, 879, 2518, 2468, 787, 1004, 717, 20, 503, 584, 2770, 284, 1935, 2098, 3223, 2771, 2147, 2543, 155999, 3592, 5504, 2216, 2871, 2509, 1720, 1760, -25, 1025, 109, 2901, 4449, 4280, 2223, 1667, 5260, 365, 1243, 1721, 517, 3266, 955, 1310, 2854, 230, 2374, 4241, 69469, 5425, 2733, 3664, 1546, 2486, 1233, 1681, 1608, 4349, 1764, 4440, 769, 2443, 3725, 2061, 216, 3489, 433, 1932, 572, 306, 623, 2288, 3370, 875, 2586, 661, 2337, 1672, 717, 1017, 1624, 3891, 2009, 3268, 1312, 229, 2597, 2114, 48369, 2609, 4265, 533, 4574, 954, 3831, 1778, 29453, 652, 2170, 3550, 1761, 805, 1615, 4153, 743, 3827, 2345, 6188, 629, 5576, 5075, 2234, 2698, 1485, 2425, 2969, 1738, 4614, 1222, 186, 2747, 2114, 4550, 1083, 822, 25805, 1741, 3438, 1501, 2284, 2384, 1031, 3213, 1894, 2280, 1610, 1766, 2269, 114, 819, 28418, 1983, 2927, 2553, 82716, 1837, 308, 2561, 70113, 5483, 81379, 1506, 190, 2701, 3062, 71, 3166, 35961, 94411, 2594, 2240, -11, 2090, 149, 855, 566, 3970, 720, 2948, 3962, 4857, 1200, 2579, 1864, 202, 51, 3628, 1872, 869, 693, 1525, 1584, 448, 714, 1000, 1983, 525, 997, 2290, 153, 1313, 3659, 4713, 979, 1010, 2105, 23483, 4651, 1178, 690, 2549, 1363, 2517, 3094, 2378, 3817, 4247, 2109, 1847, 2675, 1121, 3696, 3055, 3282, 3466, 1496, 2481, 1451, 1499, 374, 3537, 4562, 1641, 614, 137, 956, 3018, 2884, 894, 636, 255, 2311, 781, 1543, 3057, 4670, 3277, 2114, 2148, 3542, 112102, 412, 60, 922, 2999, 4258, 3267, 3039, 546, 3433, 1540, 772, 412, 758, 1571, 731, 1419, 1006, 1458, 467, 81849, 1337, 2933, 3285, 81762, 4132, 2691, 3176, 3209, 3267, 519, 4762, 1267, 3697, 1126, 1106, 2089, 16587, 46, 36353, 3514, 1110, 553, 1245, 981, 3244, 2557, 1369, 2822, 3115, 211, 1446, 936, 4420, 2670, 2020, 605, 2288, 288, 358352, 2839, 2659, 4118, 3272, 1178, 59095, 1378, 486, 180, 1190, 1648, 2286, 124, 3238, 30363, 2889, 2303, 1876, 241, 412, 3348, 2650, 1187, 4506, 2437, 3736, 1826, 4824, 364, 1980, 8374, 3198, 1235, 4727, 2956, 2360, 1746, 633, 2774, 1538, 3696, 4990, 3130, 1056, 496, 3937, 3792, 2165, 2641, 1236, 2247, 3085, 4185, 1268, 2122, 673, 1002, 1726, 4040, 2721, 645, 1743, 1097, 4393, 4668, 2188, 1105, 940, 1850, 2213, 24, 304, 1372, 2566, 86050, 621, 1643, 1110, 908, 2042, 2266, 26957, 2467, 3712, 1469, 1003, 3144, 1989, 1176, 110, 2845, 2150, 643, 3712, 2715, 944, 3298, 4915, 5474, 2652, 3960, 3510, 604, 3256, 3899, 1610, 4746, 869, 2658, 2626, 1888, 2128, 2188, 8780, 88484, 1261, 2158, 834, 1194, 1566, 878, 213, 1712, 3281, 2652, 53191, 3189, 162, 3993, 2953, 30650, 3510, 3363, 2377, 2016, 756, 421, 964, 3647, 2477, 91879, 2432, 298, 2563, 1737, 1370, 56, 2440, 93759, 1433, 2950, 5660, 992, 1574, 3361, 111654, 1318, 3188, 3041, 987, 3206, 413, 26126, 3638, 33345, 499, 1970, 1369, 1325, 582, 2850, 677, 107, 3875, 1736, 2751, 2486, 1446, 5980, 2963, 2043, 1929, 463, 4709, 1698, 1130, 1082, 1817, 1531, 1223, 970, 3227, 298041, 1955, 2064, 2050, 416, 1975, 5198, 1280, 4794, 53698, 298, 1968, 3815, 2812, 23885, 2886, 3425, 704, 660, 4792, 1259, 2091, 28279, 2377, 457, 206, 1838, 3358, 3484, 1222, 819, 1466, 603, 3393, 1154, 4181, 620, 3951, 1827, 84, 1781, 4633, 1183, 1222, 3537, 2913, 1911, 2323, 536, 1583, 1426, 598, 895, 1551, 3537, 1393, 1787, 1251, 1573, 1654, 3615, 2122, 2098, 1996, 555, 93018, 2614, 3107, 1316, 2483, 1113, 3656, 2569, 4879, 2367, 1145, 1522, 4403, 412, 21915, 2546, 974, 1229, 2808, 4005, 531, 1536, 1561, 1957, 520, 372064, 69947, 932, 2187, 10003, 2726, 4220, 1817, 1602, 1809, 3477, 869, 2569, 2945, 5664, 3028, 2573, 3236, 16356, 644, 4376, 5953, 772, 2514, 532, 5178, 19306, 1224, 2861, 2566, 2485, 373, 2333, -17, 1250, 2316, 1077, 2309, 2007, 1885, 4537, 2364, 8315, 814, 2228, 90533, 1386, 2610, 1063, 1640, 1531, 4077, 1432, 2328, 1086, 1480, 563, 1881, 4655, 2685, 4836, 2922, 3932, 3345, 1817, 241, 4729, 3184, 1943, 203, 616, 1153, 367, 159, 6289, 815, 819, 731, 1858, 958, 231, 74, 987, 4032, 1849, 4276, 2448, 85646, 2323, 1772, 2931, 1385, 1118, 1177, 4063, 1400, 4310, 5577, 802, 2616, 2223, 1207, 124, 2369, 4215, 947, 862, 2788, 4698, 5878, 1961, 7668, 1680, 1217, 3110, 1721, 1771, 481, 34069, 643, 1871, 3641, 4209, 143036, 3385, 409, 3539, 546, 5087, 2479, 4836, 2083, 54, 105, 4257, 1413, 880, 3707, 1869, 755, 1874, 4498, 2464, 2449, 1074, 18664, 190, 2596, 1337, 2621, 1697, 4322, 708, 866, 2100, 1913, 17541, 581, 573, 12692, 5801, 363, 815, 3944, 1606, 3323, 898, 2619, 4035, 5707, 2803, 142, 5963, 3336, 4589, 2681, 5601, 499, 3716, 866, 394921, 2444, 3107, 2824, 1836, 63, 2097, 444, 3329, 6070, 860, 13728, 2749, 2595, 1228, 273, 302, 2294, 4266, 21013, 115, 1307, 995, 1454, 12487, 2427, 957, 518, 2359, 3129, 1708, 4223, 2138, 4496, 3290, 2456, 639, 2795, 3529, 681, 2631, 3031, 707, 4545, 2979, 1470, 176, 3523, 770, 4528, 1498, 1900, 247, 920, 2340, 1945, 3164, 3026, 1933, 538, 2970, 20724, 962, 183, 2536, 1935, 48289, 214, 4448, 1156, 5215, 18697, 1401, 5838, 2221, 1430, 1777, 1764, 709, 3448, 1105, 1903, 1144, 5066, 4102, 3260, 114273, 4505, 4524, 1486, 1374, 3274, 2274, 175, 1807, 190, 3584, 1024, 2633, 2237, 3466, 12650, 137, 6024, 4001, 4087, 928, 2816, 92, 5319, 1233, 3041, 3074, 3815, 3434, 2084, 5289, 4457, 2875, 2384, 786, 485, 2665, 1938, 2959, 992, 2333, 92872, 1380, 6043, 739, 2953, 137, 274, 123, 2569, 45449, 619, 4771, 268, 1379, 235, 1488, 3472, 4263, 4085, 3151, 3951, 1978, 414, 4029, 4727, 1644, 1872, 2004, 380, 446, 9043, 4965, 4046, 516, 4769, 80, 3783, 85457, 3542, 3730, 1508, 169, 2380, 3085, 619, 2536, 1547, 5347, 3896, 2607, 333, 1016, 815, 1998, 5190, 1287, 3515, 178, 4092, 1427, 3414, 1917, 4244, 4069, 3958, 3013, 1063, 533, 1504, 2410, 3284, 109, 1409, 177, 3771, 342, 14560, 2278, 3575, 2944, 801, 24190, 2821, 1723, 5436, 829, 27, 999, 760, 2142, 1684, 633, 1372, 3408, 3374, 1472, 2126, 34554, 968, 2151, 4057, 3908, 1479, 3751, 1014, 2620, 31859, 1917, 2821, 1814, 2865, 918, 3106, 2365, 1858, 3050, 5877, 1599, 2388, 2405, 956, 610, 1039, 2200, 2499, 1029, 739, 2347, 2133, 1857, 314, 51, 1998, 4671, 3181, 2388, 18049, 3196, 3984, 773, 3631, 548, 614, 1498, 3101, 1888, 18041, 2665, 364, 1904, 1535, 711, 1447, 337, 2895, 3405, 1492, 24304, 1914, 3880, 4644, 4418, 520, 12180, 946, 7106, 772, 288, 2632, 92, 2596, 3781, 884, 2014, 3618, 1688, 5241, 127586, 283641, 2017, 2087, 4935, 1221, 5409, 2355, 873, 508, 1770, 134518, 2450, 3820, 62949, 21155, 262, 711, 4332, 1953, 6331, 854, 6397, 923, 1139, 2041, 1802, 3072, 21299, 2941, 3081, 2996, 1359, 2617, 3353, 1376, 2144, 3175, 118278, 29, 2259, 104, 275, 2198, 1559, 3314, 67, 2446, 2750, 4198, 3754, 1274, 2974, 67, 4212, 1571, 5553, 2205, 2016, 1764, 1974, 4514, 594472, 56, 4853, 1802, 1297, 330, 1060, 3806, 986, 1911, 452, 141, 787, 73, 320, 4934, 757, 4931, 2138, 2026, 4655, 4047, 1031, 868, 1117, 685, 2499, 347, 4899, 2813, 2161, 1250, 1840, 127571, 644, 1177, 1166, 2100, 4952, 3172, 1159, 3805, 4491, 4438, 2856, 4013, 997, 491, 1922, 3936, 1849, 14728, 7135, 1301, 836, 2366, 623, 1419, 9488, 818, 43838, 1772, 5495, 1870, 288512, 2704, 2374, 3920, 2279, 1948, 942, 1022, 325, 2431, 502, 3640, 4434, 1667, 562, 3588, 2468, 266, 4090, 166, 2326, 144584, 293, 3729, 1342, 330, 2566, 1724, 3120, 254, 4952, 13112, 6245, 1320, 3159, 950, 3849, 697, 138, 456, 568, 907, 814, 619, 689, 451, 622, 139, 5807, 5064, 3155, 3388, 3263, 3953, 3883, 4391, 5982, 6019, 1812, 1089, 2979, 1732, 2081, 1561, 2198, 706, 527, 609, 1251, 3843, 2608, 746, 419, 1293, 3664, 35, 1758, 4491, 2837, 1536, 1176, 1156, 1137, 304, 812, 911, 2364, 2099, 2869, 283, 541, 366, 3724, 90791, 2457, 1227, 2745, 2074, 1424, 881, 119, 4630, 1497, 1768, 812, 3914, 2360, 42, 3388, 765, 2836, 297, 867, 802, 741, 2678, 996, 2076, 1736, 1625, 5117, 2341, 2357, 1041, 5661, 1753, 3654, 2940, 2516, 3002, 3635, 2508, 466, 4109, 658, 3882, 1921, 2034, 3449, 5254, 3702, 888, 262, 374, 1941, 2380, 3478, 878, 938, 3208, 5743, 786, 4367, 4562, 1267, 1350, 2532, 34673, 5303, 4495, 2389, 2803, 4163, 105, 3255, 2752, 4456, 3456, 1893, 3663, 2504, 4135, 4731, 1426, 714, 1527, 19157, 6362, 718, 479, 1100, 2146, 3532, 1504, 2170, 3667, 5319, 1132, 25618, 4722, 917, 3065, 322, 5725, 501, 696, 4786, 637, 1507, 853, 2414, 3620, 1995, 22888, 1438, 3249, 1073, 4377, 1696, 1805, 3860, 3302, 1426, 1839, 3416, 653, 4242, 60548, 1085, 3058, 1608, 1267, 204, 2575, 5187, 1743, 20237, 36459, 1230, 1993, 2159, 7833, 524, 2850, 647, 4164, 3027, 1592, 210, 156645, 3212, 1682, 514, 29948, 332, 2757, 4702, 4097, 1566, 1624, 1326, 1251, 122, 540, 1129, 1368, 3392, 542, 1817, 3060, 1297, 520, 2386, 770, 1309, 6664, 3598, 1452, 2468, 2477, 2194, 2012, 4234, 1113, 1979, 45, 1627, 3265, 4647, 1811, 1153, 8145, 1757, 2553, 19619, 764, 563, 798, 389, 736, 3083, 2871, 1518, 1751, 57909, 1175, 5120, 83371, 622, 2001, 2481, 262, 524, 4123, 2248, 1834, 3150, 78, 1073, 4667, 3422, 105, 1852, 665, 1828, 2536, 1947, 3519, 573, 2246, 3421, 1534, 2125, 939, 2701, 1250, 2863, 4789, 3389, 3861, 1672, 3258, 1209, 2258, 4730, 2342, 1767, 3663, 2141, 1690, 3831, 1036, 1783, 1927, 1216, 5222, 2091, 1148, 2228, 638, 4299, 2896, 2423, 2399, 4826, 1799, 4599, 457, 1998, 134, 2726, 128, 1058, 2753, 2054, 464, 3540, 4442, 3062, 450, 1040, 2640, 1305, 732, 3240, 1846, 470, 2684, 10449, 347, 13423, 4058, 503, 3167, 3496, 3432, 1769, 1695, 1899, 199, 2682, 4709, 2887, 1346, 32503, 259, 612, 153, 1983, 4081, 3940, 5815, 108200, 239, 5441, 558, 4246, 4478, 1248, 867, 1600, 1688, 2938, 3463, 4400, 498, 1684, 13, 1571, 1039, 1353, 1021, 3824, 37, 19524, 451, 752, 1670, 631, 4297, 4505, 2093, 1124, 1060, 54598, 1336, 2831, 1424, 4612, 1377, 2624, 1866, 2850, 1906, 4314, 320, 2633, 4749, 2375, 219, 5066, 1594, 516, 5572, 4325, 1420, 2557, 3216, 430, 3648, 1730, 2317, 183, 1015, 927, 2266, 1203, 2693, 4589, 3201, 1126, 636, 4673, 3814, 1438, 2506, 1382, 4371, 67632, 4608, 1268, 3725, 833, 443, 3541, 2163, 4520, 1434, 364, 2009, 2867, 365, 1319, 734, 2543, 3190, 297, 2748, 4320, 2478, 190, 376, 473, 543, 655, 483, 2359, 15095, 2063, 4158, 4622, 1685, 250, 2272, 999, 3385, 29941, 133, 3840, 787, 534, 79245, 65092, 1270, 11372, 650, 3449, 2455, 2650, 18093, 711, 1798, 2915, 2950, 4180, 4393, 372, 368, 2326, 5935, 292, 1806, 978, 323, 5684, 1769, 1363, 3862, 1383, 3211, 26052, 33130, 2031, 3624, 2240, 3731, 2293, 403, 4261, 2677, 623, 777, 3571, 3381, 3557, 2233, 4148, 3146, 1528, 784, 4541, 613, 4743, 1258, 71, 3616, 4959, 810, 953, 3433, 342120, 290, 324, 2672, 2939, 4368, 4066, 1779, 1550, 491, 1879, 3090, 2583, 3275, 1725, 2285, 3721, 242, 3245, 1127, 3111, 709, 39, 2056, 19672, 910, 507, 3020, 3010, 2431, 491, 3265, 397, 4797, 912, 2670, 1542, 338, 2337, 1276, 2497, 93, 542, 3111, 2845, 1334, 5084, 4569, 673, 200, 4422, 481, 1701, 4487, 3429, 2998, 1560, 766, 2943, 3163, 22304, 1610, 388, 110, 4176, 3902, 3448, 1278, 1717, 129, 5473, 2667, 1697, 3751, 2269, 327, 2069, 2044, 1276, 4504, 2797, 4214, 4327, 1850, 2959, 718, 2735, 1256, 317, 3830, 921, 2464, 443, 1323, 192, 4044, 3914, 5010, 2411, 870, 222, 809, 849, 33, 1214, 2555, 1564, 962, 1929, 2685, 2154, 2353, 666, 3472, 1975, 385, 5582, 724, 3037, 680, 3533, 1802, 592, 22901, 986, 2030, 23858, 4559, 69962, 8438, 2479, 1082, 965, 721, 3004, 25994, 1566, 1223, 3151, 5213, 1691, 1690, 16, 1388, 1621, 1319, 2345, 2569, 1469, 3139, 2082, 20124, 3825, 1430, 136307, 3352, 1126, 2260, 5205, 4494, 4579, 1377, 2007, 3095, 2932, 508, 365, 7195, 224, 4991, 1648, 3275, 2548, 28916, 516, 649, 947, 259, 3992, 2198, 2566, 2781, 2203, 69276, 2940, 51114, 3355, 2948, 5709, 138, 5545, 2723, 1006, 1720, 2206, 1127, 3246, 650, 3920, 5072, 2935, 3545, 128, 2055, 1842, 145007, 1594, 4385, 261, 739, 4909, 5140, 1871, 5146, 3780, 206, 148, 637, 4329, 967, 2447, 2263, 3314, 3386, 1737, 4907, 869, 4377, 3533, 791, 3669, 5611, 3612, 381, 2609, 2310, 1272, 1479, 15671, 443, 869, 271, 3044, 964, 607, 600, 36, 2782, 4057, 1719, 264, 1360, 835, 325, 5578, 4092, 3081, 634, 1929, 2238, 2026, 3867, 2988, 4916, 1747, 3408, 3374, 417, 632, 4921, 1504, 1588, 2577, 2259, 844, 405, 1414, 23890, 1023, 1264, 3059, 1252, 598, 5456, 1976, 1433, 3763, 2067, 2985, 930, 1801, 2720, 1479, 2545, 273, 1925, 1016, 2602, 1551, 2095, 4226, 1853, 3180, 3504, 1442, 2895, 1278, 3026, 633, 2581, 3039, 349, 2431, 2673, 1628, 2720, 5887, 1390, 2103, 1509, 2353, 4936, 4793, 2327, 1011, 2866, 120, 3097, 3866, 4287, 255, 3334, 205, 1316, 2378, 3735, 594, 3490, 2115, 180697, 3673, 2676, 7999, 1546, 1539, 352, 98, 4868, 531, 334, 188650, 822, 543, 4460, 885, 3524, 1169, 275, 2446, 555, 3994, 2309, 594, 1871, 1367, 4379, 707, 638, 1280, 1380, 3528, 2236, 1503, 1503, 488, 2871, 1154, 2432, 3645, 1418, 1383, 1051, 2296, 420, 3685, 268, 448, 4098, 2888, 914, 189, 1820, 566, 52, 1647, 3863, 1614, 1042, 130, 2899, 289, 1416, 497, 4722, 3311, 945, 3034, 126, 127274, 16808, 171, 253772, 439, 1822, 1411, 1687, 2052, 4912, 1823, 503, 1986, 4164, 270, 6513, 589, 2686, 5430, 2481, 839, 2259, 185, 700, 1076, 723, 1814, 690, 3083, 3416, 800, 970, 80778, 1791, 2763, 1284, 962, 5854, 4597, 3710, 2284, 2139, 153, 1871, 2477, 2372, 3130, 4703, 4241, 2187, 1164, 873, 80, 1329, 3688, 15383, 1528, 1780, 4135, 1563, 1748, 3761, 1896, 1002, 3788, 4992, 3115, 2648, 32625, 2052, 632, 28060, 804, 498, 6369, 4274, 1036, 1001, 3690, 250, 789, 2721, 239, 1306, 774, 198, 1481, 3518, 3183, 3275, 2663, 2016, 52, 5303, 2482, 1829, 2474, 82004, 248, 1767, 3518, 2950, 1887, 1552, 2583, 2672, 5226, 1419, 1838, 4104, 5180, 2798, 547, 414, 911, 3764, 1193, 854, 2185, 2537, 2085, 1141, 2454, 2036, 2952, 731, 5502, 581, 2049, 3662, 1215, 3723, 3465, 574, 2178, 4365, 1101, 2975, 4647, 4300, 1316, 1807, 3631, 3460, 639, 120, 971, 1832, 895, 2415, 3490, 1822, 5223, 1928, 716, 3449, 526, 721, 1896, 2171, 4777, 2397, 429, 1236, 2928, 1581, 1460, 87, 2857, 1574, 2604, 1505, 2577, 2528, 2325, 2674, 2793, 1897, 1011, 4041, 746, 3205, 320, 2527, 1156, 1236, 2708, 909, 2221, 1808, 1753, 5203, 3806, 898, 86610, 969, 1303, 3060, 444, 2106, 23573, 21708, 732, 2431, 938, 15420, 20932, 2300, 1999, 363, 3090, 19, 514, 1971, 3174, 2041, 4001, 1854, 3591, 1161, 4339, 4950, 3387, 1441, 5106, 4551, 1373, 2332, 43, 2340, 3330, 1646, 3227, 1914, 3520, 526, 502, 1702, 4083, 2688, 2944, 2943, 1313, 2662, 736, 2669, 2707, 6755, 3898, 811, 6084, 4241, 2900, 2486, 865, 2112, 1555, 231, 25430, 1248, 3924, 3786, 310, 30691, 20199, 578, 1692, 5357, 4008, 2929, 10173, 3332, 3296, 2327, 1905, 1341, 1570, 865, 4581, 1979, 916, 3673, 436, 2732, 2491, 2466, 3334, 3503, 627, 4444, 162, 1380, 5744, 2440, 3684, 492, 1856, 869, 749, 144, 2389, 3427, 1337, 1756, 4104, 3160, 8622, 868, 6499, 2943, 1124, 1851, 1868, 1108, 12341, 3529, 77, 1484, 4884, 1093, 49, 2560, 23645, 1367, 796, 2898, 422, 1229, 2928, 2043, 3733, 12104, 1250, 198, 2329, 395, 3296, 736, 1441, 3845, 4489, 4399, 3770, 3089, 163, 1172, 1456, 467, 885, 180, 3118, 3338, 2316, 2916, 1811, 455, 2353, 4703, 662, 4813, 1236, 146, 483, 1136, 1070, 1278, 3694, 16006, 4117, 1999, 5266, 2391, 2434, 4798, 1531, 75457, 3287, 1171, 5100, 230, 1763, 1197, 1055, 501, 482, 4065, 517884, 2977, 2315, 68, 5110, 155, 63, 2620, 71, 1332, 2603, 3274, 487, 2486, 2730, 4488, 1236, 3012, 2042, 1113, 1512, 2967, 77, 2140, 4239, 1652, 2897, 29555, 1721, 314, 1463, 1901, 562, 1941, 5418, 2482, 2931, 3455, 294, 484, 197, 2174, 1542, 186, 1303, 2575, 3317, 1628, 2317, 4106, 2070, 80343, 996, 2913, 111922, 107586, 2327, 4645, 1506, 1704, 3074, 52913, 214, 1700, 3032, 2122, 8699, 8948, 1848, 801, 1960, 3202, 3009, 20682, 5538, 5449, 2345, 3173, 1873, 289, 4723, 2012, 1165, 3991, 5754, 1139, 2888, 2211, 4463, 1970, 983, 1018, 1034, 3883, 93, 1972, 1124, 2525, 3399, 2788, 2399, 5696, 3997, 378, 5502, 3427, 968, 1535, 1626, 3172, 184, 996, 3304, 126451, 2875, 3806, 1948, 862, 1453, 2632, 1698, 2563, 2631, 7592, 112639, 1318, 19, 125501, 2559, 2601, 131, 622, 1313, 21530, 3267, -26, 2159, 700, 2445, 203, 2769, 5238, 2280, 1110, 2005, 3236, 2060, 1951, 3198, 3360, 4516, 964, 3010, 224, 1897, 1508, 5256, 2616, 4185, 5563, 61, 2219, 5384, 2970, 1587, 4227, 102725, 3411, 25536, 405, 2601, 3931, 2532, 5664, 1149, 1291, 75, 2586, 1493, 142, 1038, 6682, 181, 2395, 478, 1998, 1136, 1065, 1307, 1939, 3073, 3786, 2142, 2182, 3413, 2024, 2835, 3174, 906, 1048, 4430, 3052, 351, 5081, 2690, 1337, 1734, 201, 2618, 1219, 691, 3248, 3765, 2217, 4138, 2207, 1666, 3138, 51569, 727, 1208, 1888, 1327, 374, 2587, 3115, 2303, 3244, 1151, 420, 511, 645, 3461, 3725, 2611, 5174, 638, 30339, 3839, 7407, 147, 48, 3578, 77234, 929, 3143, 1475, 3394, 1348, 2148, 1324, 5463, 1383, 558, 1615, 1717, 2851, 1760, 1469, 2749, 802, 79, 692, 3923, 1276, 518, 1897, 361, 1654, 2984, 13502, 2396, 2511, 3053, 886, 1691, 2437, 4325, 2929, 2958, 1488, 803, 177, 1635, 1112, 5395, 3833, 3751, 504, 2081, 4413, 4381, 911, 2745, 645, 1995, 4393, 2154, 3459, 3605, 6281, 4119, 1529, 1874, 1924, 111, 1057, 1965, 2261, 2634, 2727, 77715, 1016, 3850, 1828, 4328, 250, 724, 2678, 2927, 3214, 318, 337, 147, 1185, 2563, 861, 1468, 1600, 1533, 169, 1696, 2591, 23874, 793, 12203, 2374, 2086, 1684, 1983, 60, 2739, 2930, 915, 223, 1395, 1056, 1547, 3530, 6790, 2686, 57, 713, 2602, 61396, 1305, 4639, 2641, 2631, 3158, 2496, 2582, 3441, 1220, 614, 434, 1270, 2405, 595, 3912, 1652, 1336, 4576, 1898, 970, 175, 604, 3014, 4134, 2353, 4704, 5025, 6908, 2905, 349050, 2351, 2603, 4396, 2002, 802, 963, 657, 2382, 18990, 73, 2281, 1779, 524, 5572, 2450, 1827, 4412, 1582, 525, 850, 4465, 2490, 2963, 3375, 1236, 3735, 554, 4004, 168, 1072, 100070, 777, 3896, 453, 3360, 1454, 1717, 19, 1923, 535, 3817, 3968, 4235, 1536, 710, 1827, 438, 4329, 2586, 5232, 3431, 1672, 3403, 10284, 1505, 2462, 3450, 3103, 2658, 3364, 3089, 1979, 2426, 254, 2626, 1202, 190, 106, 1572, 141, 3300, 591, 1144, 310, 2516, 80498, 3868, 5711, 2560, 3925, 4133, 1709, 1132, 1527, 1555, 399, 1391, 4106, 3043, 2033, 648, 10768, 741, 2066, 2114, 4649, 264, 840, 3239, 3388, 1512, 18043, 2039, 1890, 2597, 2334, 3869, 3124, 1388, 116, 3826, 334, 2380, 553, 877, 4867, 51222, 6292, 1318, 3212, 84, 2215, 5117, 3281, 1600, 68241, 1685, 985, 2862, 578, 3179, 21531, 2567, 5147, 2462, 4568, 2147, 1481, 18142, 3880, 2940, 3178, 2008, 2146, 3597, 3592, 495, 91, 1449, 2683, 627, 2351, 1498, 625, 4229, 824, 450, 1992, 6081, 122, 1856, 13708, 1871, 2519, 5040, 2028, 586, 2904, 3774, 3305, 1638, 3581, 3176, 1245, 475, 4138, 4881, 2659, 2008, 3856, 834, 3826, 1681, 569, 4949, 2025, 62, 3308, 4959, 3551, 2336, 3673, 1709, 1354, 30923, 650, 682, 409, 223, 3554, 2828, 3534, 2609, 1689, 2786, 4031, 1813, 1347, 3069, 4312, 908, 16749, 3332, 771, 906, 5023, 242, 4702, 1157, 2070, 981, 2869, 103, 5563, 967, 2701, 1938, 46537, 1877, 2190, 5357, 640, 384, 1074, 143, 2131, 976, 2111, 194, 3360, 3876, 1660, 2774, 3424, 3590, 2643, 5841, 2365, 1931, 546, 1470, 5077, 970, 57, 28257, 3266, 2959, 3351, 4257, 10185, 1157, 734, 517, 1060, 1615, 222, 4307, 3184, 1883, 387, 180, 3509, 4386, 1122, 124

In [43]:
df['no_of_employees'].max()

602069

In [44]:
df['no_of_employees'].min()

-26