In [2]:
print("ok")

ok

In [4]:
import pandas as pd

df = pd.read_csv("Visadataset.csv")
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [5]:
df.shape

(25480, 12)

In [6]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [7]:
data= df.to_dict(orient="records")
data

[{'case_id': 'EZYV01',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 14513,
  'yr_of_estab': 2007,
  'region_of_employment': 'West',
  'prevailing_wage': 592.2029,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV02',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2412,
  'yr_of_estab': 2002,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 83425.65,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV03',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 44444,
  'yr_of_estab': 2008,
  'region_of_employment': 'West',
  'prevailing_wage': 122996.86,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV04',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 98,
  'yr_of_estab': 1897,
  'region_of_employment': 'West',
  'prevailing_wage': 83434.03,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV05',
  'continent': 'Africa',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1082,
  'yr_of_estab': 2005,
  'region_of_employment': 'South',
  'prevailing_wage': 149907.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV06',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2339,
  'yr_of_estab': 2012,
  'region_of_employment': 'South',
  'prevailing_wage': 78252.14,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV07',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 4985,
  'yr_of_estab': 1994,
  'region_of_employment': 'South',
  'prevailing_wage': 53635.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV08',
  'continent': 'North America',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3035,
  'yr_of_estab': 1924,
  'region_of_employment': 'West',
  'prevailing_wage': 418.2298,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV09',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 4810,
  'yr_of_estab': 2012,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 74362.19,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV10',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2251,
  'yr_of_estab': 1995,
  'region_of_employment': 'South',
  'prevailing_wage': 67514.76,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV11',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2465,
  'yr_of_estab': 2004,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 83588.56,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV12',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4069,
  'yr_of_estab': 2005,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 70813.09,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV13',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 123876,
  'yr_of_estab': 1963,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 28663.05,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV14',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1652,
  'yr_of_estab': 2007,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 107196.03,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV15',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 15756,
  'yr_of_estab': 2006,
  'region_of_employment': 'South',
  'prevailing_wage': 220081.73,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV16',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4897,
  'yr_of_estab': 1987,
  'region_of_employment': 'West',
  'prevailing_wage': 74108.02,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV17',
  'continent': 'Europe',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 76638,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 3706.79,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV18',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2747,
  'yr_of_estab': 2001,
  'region_of_employment': 'West',
  'prevailing_wage': 16132.61,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV19',
  'continent': 'Africa',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 4743,
  'yr_of_estab': 2004,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 150441.13,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV20',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 843,
  'yr_of_estab': 1972,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 79948.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV21',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 880,
  'yr_of_estab': 2008,
  'region_of_employment': 'West',
  'prevailing_wage': 71128.98,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV22',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1706,
  'yr_of_estab': 2013,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 137694.98,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV23',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2878,
  'yr_of_estab': 1968,
  'region_of_employment': 'West',
  'prevailing_wage': 45642.39,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV24',
  'continent': 'North America',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1517,
  'yr_of_estab': 1884,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 90108.38,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV25',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 241,
  'yr_of_estab': 1981,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 71286.04,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV26',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1100,
  'yr_of_estab': 1997,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 99489.65,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV27',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 756,
  'yr_of_estab': 1995,
  'region_of_employment': 'South',
  'prevailing_wage': 86332.95,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV28',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 2889,
  'yr_of_estab': 2005,
  'region_of_employment': 'South',
  'prevailing_wage': 103029.33,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV29',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 18,
  'yr_of_estab': 2004,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 40925.86,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV30',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 758,
  'yr_of_estab': 2009,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 189190.48,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV31',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1408,
  'yr_of_estab': 1998,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 79594.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV32',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 995,
  'yr_of_estab': 1880,
  'region_of_employment': 'South',
  'prevailing_wage': 135866.13,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV33',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2415,
  'yr_of_estab': 1963,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 72077.57,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV34',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 2395,
  'yr_of_estab': 2000,
  'region_of_employment': 'South',
  'prevailing_wage': 81921.18,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV35',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1809,
  'yr_of_estab': 2010,
  'region_of_employment': 'South',
  'prevailing_wage': 225569.73,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV36',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 5512,
  'yr_of_estab': 2001,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 92421.92,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV37',
  'continent': 'Europe',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2520,
  'yr_of_estab': 1981,
  'region_of_employment': 'West',
  'prevailing_wage': 2490.12,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV38',
  'continent': 'Europe',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 44,
  'yr_of_estab': 1965,
  'region_of_employment': 'South',
  'prevailing_wage': 110817.26,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV39',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 2206,
  'yr_of_estab': 1909,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 50960.01,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV40',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 3729,
  'yr_of_estab': 2007,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 125336.9,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV41',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3723,
  'yr_of_estab': 2011,
  'region_of_employment': 'West',
  'prevailing_wage': 39633.32,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV42',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 1209,
  'yr_of_estab': 1989,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 156326.33,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV43',
  'continent': 'Europe',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 19770,
  'yr_of_estab': 2005,
  'region_of_employment': 'West',
  'prevailing_wage': 43630.58,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV44',
  'continent': 'North America',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2582,
  'yr_of_estab': 1989,
  'region_of_employment': 'South',
  'prevailing_wage': 54614.42,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV45',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 5407,
  'yr_of_estab': 1998,
  'region_of_employment': 'West',
  'prevailing_wage': 28989.87,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV46',
  'continent': 'Europe',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 2092,
  'yr_of_estab': 1998,
  'region_of_employment': 'South',
  'prevailing_wage': 22924.91,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV47',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2623,
  'yr_of_estab': 2008,
  'region_of_employment': 'South',
  'prevailing_wage': 61567.75,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV48',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 226,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 156251.17,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV49',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2405,
  'yr_of_estab': 1933,
  'region_of_employment': 'South',
  'prevailing_wage': 86022.02,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV50',
  'continent': 'Asia',
  'education_of_employee': 'Doctorate',
  'has_job_experience': 'N',
  'requires_job_training': 'Y',
  'no_of_employees': 2171,
  'yr_of_estab': 1960,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 49565.37,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Denied'},
 {'case_id': 'EZYV51',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 746,
  'yr_of_estab': 1991,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 66191.41,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV52',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 3129,
  'yr_of_estab': 2003,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 95623.2,
  'unit_of_wage': 'Year',
  'full_time_position': 'N',
  'case_status': 'Certified'},
 {'case_id': 'EZYV53',
  'continent': 'Asia',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'N',
  'requires_job_training': 'N',
  'no_of_employees': 1647,
  'yr_of_estab': 1998,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 115014.05,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV54',
  'continent': 'Asia',
  'education_of_employee': 'High School',
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2438,
  'yr_of_estab': 1976,
  'region_of_employment': 'Midwest',
  'prevailing_wage': 35018.04,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV55',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 11733,
  'yr_of_estab': 1995,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 230.8072,
  'unit_of_wage': 'Hour',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV56',
  'continent': 'Asia',
  'education_of_employee': "Master's",
  'has_job_experience': 'Y',
  'requires_job_training': 'N',
  'no_of_employees': 2368,
  'yr_of_estab': 1998,
  'region_of_employment': 'Northeast',
  'prevailing_wage': 113799.64,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',
  'case_status': 'Certified'},
 {'case_id': 'EZYV57',
  'continent': 'Europe',
  'education_of_employee': "Bachelor's",
  'has_job_experience': 'Y',
  'requires_job_training': 'Y',
  'no_of_employees': 779,
  'yr_of_estab': 1994,
  'region_of_employment': 'West',
  'prevailing_wage': 85854.09,
  'unit_of_wage': 'Year',
  'full_time_position': 'Y',

In [8]:
len(data)

25480

In [ ]:
DB_NAME ="US_VISA"
COLLECTION_NAME = "visa_data"
CONNECTION_URL ="mongodb+srv://snehalj2201_db_user:snehalj2201_db_user@cluster0.ahfua0s.mongodb.net/?appName=Cluster0"

In [10]:
import pymongo

In [11]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

rec = collection.insert_many(data)

OperationFailure: bad auth : authentication failed, full error: {'ok': 0, 'errmsg': 'bad auth : authentication failed', 'code': 8000, 'codeName': 'AtlasError'}

In [ ]:
records = collection.find()
records

In [ ]:
for i,j in enumerate (records):
    print(f"{i}:{j}")

0:{'_id': ObjectId('698f0f648e779f1f7aa0eb6c'), 'case_id': 'EZYV31', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1408, 'yr_of_estab': 1998, 'region_of_employment': 'Midwest', 'prevailing_wage': 79594.12, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
1:{'_id': ObjectId('698f0f648e779f1f7aa0eb7e'), 'case_id': 'EZYV49', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2405, 'yr_of_estab': 1933, 'region_of_employment': 'South', 'prevailing_wage': 86022.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
2:{'_id': ObjectId('698f0f648e779f1f7aa0eb7f'), 'case_id': 'EZYV50', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 2171, 'yr_of_estab': 1960, 'region_of_employment': 'Northeast', 'prevailing_wage': 49565.37, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
3:{'_id': ObjectId('698f0f648e779f1f7aa0eb84'), 'case_id': 'EZYV55', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 11733, 'yr_of_estab': 1995, 'region_of_employment': 'Northeast', 'prevailing_wage': 230.8072, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Certified'}
4:{'_id': ObjectId('698f0f648e779f1f7aa0eb87'), 'case_id': 'EZYV58', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2825, 'yr_of_estab': 1996, 'region_of_employment': 'Northeast', 'prevailing_wage': 14174.04, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
5:{'_id': ObjectId('698f0f648e779f1f7aa0eb88'), 'case_id': 'EZYV59', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3510, 'yr_of_estab': 2007, 'region_of_employment': 'West', 'prevailing_wage': 47176.84, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
6:{'_id': ObjectId('698f0f648e779f1f7aa0eb8b'), 'case_id': 'EZYV62', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2311, 'yr_of_estab': 1994, 'region_of_employment': 'Midwest', 'prevailing_wage': 58791.58, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
7:{'_id': ObjectId('698f0f648e779f1f7aa0eb9d'), 'case_id': 'EZYV80', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 1062, 'yr_of_estab': 1998, 'region_of_employment': 'West', 'prevailing_wage': 194176.83, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
8:{'_id': ObjectId('698f0f648e779f1f7aa0eb9e'), 'case_id': 'EZYV81', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 32619, 'yr_of_estab': 1947, 'region_of_employment': 'South', 'prevailing_wage': 102073.81, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
9:{'_id': ObjectId('698f0f648e779f1f7aa0eba1'), 'case_id': 'EZYV84', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2359, 'yr_of_estab': 2007, 'region_of_employment': 'Northeast', 'prevailing_wage': 84125.48, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
10:{'_id': ObjectId('698f0f648e779f1f7aa0eba2'), 'case_id': 'EZYV85', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 1023, 'yr_of_estab': 2002, 'region_of_employment': 'South', 'prevailing_wage': 174014.59, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
11:{'_id': ObjectId('698f0f648e779f1f7aa0eba5'), 'case_id': 'EZYV88', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4455, 'yr_of_estab': 1998, 'region_of_employment': 'West', 'prevailing_wage': 113327.34, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
12:{'_id': ObjectId('698f0f648e779f1f7aa0ebab'), 'case_id': 'EZYV94', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 488, 'yr_of_estab': 2010, 'region_of_employment': 'Midwest', 'prevailing_wage': 49357.95, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
13:{'_id': ObjectId('698f0f648e779f1f7aa0ebb5'), 'case_id': 'EZYV104', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 367, 'yr_of_estab': 1982, 'region_of_employment': 'West', 'prevailing_wage': 115235.95, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
14:{'_id': ObjectId('698f0f648e779f1f7aa0ebc1'), 'case_id': 'EZYV116', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3323, 'yr_of_estab': 2005, 'region_of_employment': 'Midwest', 'prevailing_wage': 57590.66, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
15:{'_id': ObjectId('698f0f648e779f1f7aa0ebc2'), 'case_id': 'EZYV117', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 509, 'yr_of_estab': 1997, 'region_of_employment': 'South', 'prevailing_wage': 32400.2, 'unit_of_wage': 'Week', 'full_time_position': 'Y', 'case_status': 'Certified'}
16:{'_id': ObjectId('698f0f648e779f1f7aa0ebca'), 'case_id': 'EZYV125', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 960, 'yr_of_estab': 2012, 'region_of_employment': 'Northeast', 'prevailing_wage': 40256.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
17:{'_id': ObjectId('698f0f648e779f1f7aa0ebe5'), 'case_id': 'EZYV152', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2261, 'yr_of_estab': 1966, 'region_of_employment': 'Midwest', 'prevailing_wage': 68933.4, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
18:{'_id': ObjectId('698f0f648e779f1f7aa0ebf1'), 'case_id': 'EZYV164', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 816, 'yr_of_estab': 1947, 'region_of_employment': 'South', 'prevailing_wage': 113212.16, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
19:{'_id': ObjectId('698f0f648e779f1f7aa0ec02'), 'case_id': 'EZYV181', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 44069, 'yr_of_estab': 2006, 'region_of_employment': 'West', 'prevailing_wage': 134350.49, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
20:{'_id': ObjectId('698f0f648e779f1f7aa0ec06'), 'case_id': 'EZYV185', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 654, 'yr_of_estab': 1954, 'region_of_employment': 'Northeast', 'prevailing_wage': 128173.92, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
21:{'_id': ObjectId('698f0f648e779f1f7aa0ec15'), 'case_id': 'EZYV200', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 7320, 'yr_of_estab': 1868, 'region_of_employment': 'Northeast', 'prevailing_wage': 89207.07, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
22:{'_id': ObjectId('698f0f648e779f1f7aa0ec1d'), 'case_id': 'EZYV208', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1190, 'yr_of_estab': 2003, 'region_of_employment': 'South', 'prevailing_wage': 82464.74, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
23:{'_id': ObjectId('698f0f648e779f1f7aa0ec24'), 'case_id': 'EZYV215', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2778, 'yr_of_estab': 2000, 'region_of_employment': 'Northeast', 'prevailing_wage': 146374.48, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
24:{'_id': ObjectId('698f0f648e779f1f7aa0ec26'), 'case_id': 'EZYV217', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1515, 'yr_of_estab': 2001, 'region_of_employment': 'Midwest', 'prevailing_wage': 269321.68, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
25:{'_id': ObjectId('698f0f648e779f1f7aa0ec27'), 'case_id': 'EZYV218', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 26891, 'yr_of_estab': 1917, 'region_of_employment': 'Northeast', 'prevailing_wage': 52114.54, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
26:{'_id': ObjectId('698f0f648e779f1f7aa0ec2a'), 'case_id': 'EZYV221', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 879, 'yr_of_estab': 1996, 'region_of_employment': 'Midwest', 'prevailing_wage': 141796.39, 'unit_of_wage': 'Month', 'full_time_position': 'Y', 'case_status': 'Certified'}
27:{'_id': ObjectId('698f0f648e779f1f7aa0ec2b'), 'case_id': 'EZYV222', 'continent': 'North America', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2518, 'yr_of_estab': 2010, 'region_of_employment': 'South', 'prevailing_wage': 219529.62, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
28:{'_id': ObjectId('698f0f648e779f1f7aa0ec42'), 'case_id': 'EZYV245', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1760, 'yr_of_estab': 1997, 'region_of_employment': 'South', 'prevailing_wage': 63108.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
29:{'_id': ObjectId('698f0f648e779f1f7aa0ec4b'), 'case_id': 'EZYV254', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5260, 'yr_of_estab': 1994, 'region_of_employment': 'West', 'prevailing_wage': 91689.54, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
30:{'_id': ObjectId('698f0f648e779f1f7aa0ec4f'), 'case_id': 'EZYV258', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 517, 'yr_of_estab': 1949, 'region_of_employment': 'South', 'prevailing_wage': 21651.43, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
31:{'_id': ObjectId('698f0f648e779f1f7aa0ec50'), 'case_id': 'EZYV259', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3266, 'yr_of_estab': 2007, 'region_of_employment': 'Midwest', 'prevailing_wage': 102598.35, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
32:{'_id': ObjectId('698f0f648e779f1f7aa0ec51'), 'case_id': 'EZYV260', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 955, 'yr_of_estab': 1998, 'region_of_employment': 'West', 'prevailing_wage': 56422.81, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
33:{'_id': ObjectId('698f0f648e779f1f7aa0ec5e'), 'case_id': 'EZYV273', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1681, 'yr_of_estab': 1999, 'region_of_employment': 'West', 'prevailing_wage': 85218.35, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
34:{'_id': ObjectId('698f0f648e779f1f7aa0ec64'), 'case_id': 'EZYV279', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2443, 'yr_of_estab': 1958, 'region_of_employment': 'Midwest', 'prevailing_wage': 99714.22, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
35:{'_id': ObjectId('698f0f648e779f1f7aa0ec6a'), 'case_id': 'EZYV285', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1932, 'yr_of_estab': 1989, 'region_of_employment': 'South', 'prevailing_wage': 165.2722, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Certified'}
36:{'_id': ObjectId('698f0f648e779f1f7aa0ec7e'), 'case_id': 'EZYV305', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2114, 'yr_of_estab': 1977, 'region_of_employment': 'West', 'prevailing_wage': 596.2488, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Certified'}
37:{'_id': ObjectId('698f0f648e779f1f7aa0ec80'), 'case_id': 'EZYV307', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2609, 'yr_of_estab': 1991, 'region_of_employment': 'Northeast', 'prevailing_wage': 34738.65, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
38:{'_id': ObjectId('698f0f648e779f1f7aa0ec82'), 'case_id': 'EZYV309', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 533, 'yr_of_estab': 1978, 'region_of_employment': 'West', 'prevailing_wage': 30066.16, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
39:{'_id': ObjectId('698f0f648e779f1f7aa0ec83'), 'case_id': 'EZYV310', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4574, 'yr_of_estab': 2006, 'region_of_employment': 'Northeast', 'prevailing_wage': 67204.54, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
40:{'_id': ObjectId('698f0f648e779f1f7aa0ec86'), 'case_id': 'EZYV313', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1778, 'yr_of_estab': 1983, 'region_of_employment': 'South', 'prevailing_wage': 100850.52, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
41:{'_id': ObjectId('698f0f648e779f1f7aa0ec88'), 'case_id': 'EZYV315', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 652, 'yr_of_estab': 1913, 'region_of_employment': 'Northeast', 'prevailing_wage': 24968.7, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Denied'}
42:{'_id': ObjectId('698f0f648e779f1f7aa0ec8a'), 'case_id': 'EZYV317', 'continent': 'North America', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3550, 'yr_of_estab': 2012, 'region_of_employment': 'West', 'prevailing_wage': 268.1379, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Certified'}
43:{'_id': ObjectId('698f0f648e779f1f7aa0eca5'), 'case_id': 'EZYV344', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1741, 'yr_of_estab': 1950, 'region_of_employment': 'Northeast', 'prevailing_wage': 20687.36, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
44:{'_id': ObjectId('698f0f648e779f1f7aa0eca8'), 'case_id': 'EZYV347', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2284, 'yr_of_estab': 2013, 'region_of_employment': 'South', 'prevailing_wage': 51610.24, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
45:{'_id': ObjectId('698f0f648e779f1f7aa0ecae'), 'case_id': 'EZYV353', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1610, 'yr_of_estab': 1962, 'region_of_employment': 'Midwest', 'prevailing_wage': 98331.32, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
46:{'_id': ObjectId('698f0f648e779f1f7aa0ecb7'), 'case_id': 'EZYV362', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 82716, 'yr_of_estab': 1993, 'region_of_employment': 'West', 'prevailing_wage': 111724.66, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
47:{'_id': ObjectId('698f0f648e779f1f7aa0ecc6'), 'case_id': 'EZYV377', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2594, 'yr_of_estab': 1849, 'region_of_employment': 'South', 'prevailing_wage': 85495.84, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
48:{'_id': ObjectId('698f0f648e779f1f7aa0ecc9'), 'case_id': 'EZYV380', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2090, 'yr_of_estab': 1872, 'region_of_employment': 'West', 'prevailing_wage': 197452.18, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
49:{'_id': ObjectId('698f0f648e779f1f7aa0eccd'), 'case_id': 'EZYV384', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3970, 'yr_of_estab': 2013, 'region_of_employment': 'West', 'prevailing_wage': 74603.2, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
50:{'_id': ObjectId('698f0f648e779f1f7aa0ecd2'), 'case_id': 'EZYV389', 'continent': 'North America', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1200, 'yr_of_estab': 1996, 'region_of_employment': 'Midwest', 'prevailing_wage': 107875.51, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
51:{'_id': ObjectId('698f0f648e779f1f7aa0ecdc'), 'case_id': 'EZYV399', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1584, 'yr_of_estab': 1984, 'region_of_employment': 'Midwest', 'prevailing_wage': 45261.26, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
52:{'_id': ObjectId('698f0f648e779f1f7aa0ece0'), 'case_id': 'EZYV403', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1983, 'yr_of_estab': 2002, 'region_of_employment': 'South', 'prevailing_wage': 33049.76, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}

AutoReconnect: ac-irgmqmd-shard-00-02.ahfua0s.mongodb.net:27017: [WinError 10053] An established connection was aborted by the software in your host machine (configured timeouts: connectTimeoutMS: 20000.0ms)

In [ ]:
df =pd.DataFrame(list(collection.find()))
df.head()

,_id,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,698f0f648e779f1f7aa0eb6c,EZYV31,Asia,Master's,Y,N,1408,1998,Midwest,79594.1200,Year,N,Certified
1,698f0f648e779f1f7aa0eb7e,EZYV49,Asia,Bachelor's,Y,N,2405,1933,South,86022.0200,Year,Y,Certified
2,698f0f648e779f1f7aa0eb7f,EZYV50,Asia,Doctorate,N,Y,2171,1960,Northeast,49565.3700,Year,Y,Denied
3,698f0f648e779f1f7aa0eb84,EZYV55,Asia,Master's,Y,N,11733,1995,Northeast,230.8072,Hour,Y,Certified
4,698f0f648e779f1f7aa0eb87,EZYV58,Asia,Bachelor's,Y,N,2825,1996,Northeast,14174.0400,Year,Y,Certified

In [ ]:
if "_id" in df.columns.to_list():
    df = df.drop(columns=["_id"],axis =1) #to remove above _id column

In [ ]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV31,Asia,Master's,Y,N,1408,1998,Midwest,79594.1200,Year,N,Certified
1,EZYV49,Asia,Bachelor's,Y,N,2405,1933,South,86022.0200,Year,Y,Certified
2,EZYV50,Asia,Doctorate,N,Y,2171,1960,Northeast,49565.3700,Year,Y,Denied
3,EZYV55,Asia,Master's,Y,N,11733,1995,Northeast,230.8072,Hour,Y,Certified
4,EZYV58,Asia,Bachelor's,Y,N,2825,1996,Northeast,14174.0400,Year,Y,Certified

In [ ]:
## If you are getting timeout issue

import certifi
client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())
# TO CREATE THE DATABASE
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]
# TO INSERT DATA INTO THE COLLECTION
rec = collection.insert_many(data)

BulkWriteError: batch op errors occurred, full error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': "E11000 duplicate key error collection: US_VISA.visa_data index: _id_ dup key: { _id: ObjectId('69a7d5134d39781d6224a916') }", 'keyPattern': {'_id': 1}, 'keyValue': {'_id': ObjectId('69a7d5134d39781d6224a916')}, 'op': {'case_id': 'EZYV01', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 14513, 'yr_of_estab': 2007, 'region_of_employment': 'West', 'prevailing_wage': 592.2029, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied', '_id': ObjectId('69a7d5134d39781d6224a916')}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}